name: News Crawler

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行
  workflow_dispatch:

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          cd crawler
          pip install -r requirements.txt
      
      - name: Run news crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd crawler
          python rss_news_crawler.py
          
